export const BaseEvents = {
  ENGINE_INITIALIZED: 'ENGINE_INITIALIZED',
  ENGINE_DESTROYED: 'ENGINE_DESTROYED',
  ENGINE_ERROR: 'ENGINE_ERROR',
  NETWORK_STATUS_CHANGED: 'NETWORK_STATUS_CHANGED',
  SYNC_STARTED: 'SYNC_STARTED',
  SYNC_COMPLETED: 'SYNC_COMPLETED',
} as const;
