export const ChatEvents = {
  MESSAGE_SENT: 'CHAT_MESSAGE_SENT',
  MESSAGE_RECEIVED: 'CHAT_MESSAGE_RECEIVED',
  MESSAGE_DELETED: 'CHAT_MESSAGE_DELETED',
  MESSAGE_EDITED: 'CHAT_MESSAGE_EDITED',
  REACTION_UPDATED: 'CHAT_REACTION_UPDATED',
  CONVERSATIONS_UPDATED: 'CHAT_CONVERSATIONS_UPDATED',
  TYPING_STATUS_CHANGED: 'CHAT_TYPING_STATUS_CHANGED',
} as const;
